// src/renderer/components/vega/contextmenu/ContextMenu.vue
<template>
  <sp-menu v-if="isOpen" ref="el" class="contextmenu" :style="style">
    <div v-for="(item, i) in items" :key="i">
      <sp-action-button size="S" :quiet="true" @click="(e) => click(e, item)">
        {{ item.text }}
      </sp-action-button>
    </div>
  </sp-menu>
</template>

<style scoped>
.contextmenu {
  background-color: var(
    --spectrum-alias-background-color-default,
    var(--spectrum-global-color-gray-100)
  );
  position: fixed;
  z-index: 10;
}
</style>

<script lang="ts">
import Vue from "vue";
import { Component } from "vue-property-decorator";

export class ContextMenuItem {
  text: string = "";
  action: (e: Event) => void = () => {};
}

@Component({})
export default class ContextMenu extends Vue {
  x: number = 0;
  y: number = 0;
  isOpen: boolean = false;

  items: ContextMenuItem[] = [];

  get style(): Partial<CSSStyleDeclaration> {
    return {
      left: this.x + "px",
      top: this.y + "px",
    };
  }

  click(e: Event, item: ContextMenuItem) {
    item.action(e);
    this.close();
  }

  close() {
    this.isOpen = false;
    window.removeEventListener("mousedown", this.mouseDownInWindow);
  }

  mouseDownInWindow(e: MouseEvent) {
    const target = e.target as HTMLElement;
    // @ts-ignore
    const el = this.$refs.el.$el as HTMLElement;
    if (el.contains(target)) {
      return;
    }
    this.close();
  }

  open(e: MouseEvent, items: ContextMenuItem[]) {
    window.addEventListener("mousedown", this.mouseDownInWindow);
    this.items = items;
    this.isOpen = true;
    this.x = e.pageX;
    this.y = e.pageY;
    this.$nextTick(() => {
      const rect = this.$el.getBoundingClientRect();
      const diff = rect.height + rect.top - window.innerHeight;
      if (diff > 0) {
        this.y -= diff;
      }
    });
  }
}
</script>

// src/components/core/context_menu/ContextMenu.tsx
import React, { PropsWithChildren, useRef } from "react";
import styled from "styled-components";

interface ContextMenuProps {
  show: boolean;
  e?: React.MouseEvent<HTMLDivElement, MouseEvent>;
  onClose: () => void;
}

const StyledDiv = styled.div.attrs<{
  x: number;
  y: number;
}>((p) => {
  return {
    style: {
      left: p.x + "px",
      top: p.y + "px",
    },
  };
})<{ x: number; y: number }>`
  position: fixed;
  background-color: var(--color-background-2);
  border: 1px solid var(--color-border);
  color: var(--color-text);
  font-size: 12px;
  line-height: 12px;
  border-radius: 4px;
  padding: 4px 4px;
  z-index: 10000;
`;

export const ContextMenu: React.FC<PropsWithChildren<ContextMenuProps>> = (
  props
) => {
  const ref = useRef<HTMLDivElement>(null);
  if (!props.show) return null;
  const mouseDown = (e: MouseEvent) => {
    if (ref.current?.contains(e.target as Node)) {
      return;
    }
    props.onClose();
    window.removeEventListener("mousedown", mouseDown);
  };
  window.addEventListener("mousedown", mouseDown);
  return (
    <>
      <Overlay />
      <StyledDiv x={props.e?.pageX ?? 0} y={props.e?.pageY || 0} ref={ref}>
        {props.children}
      </StyledDiv>
    </>
  );
};

const Overlay = styled.div`
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  z-index: 1000;
  background-color: rgba(0, 0, 0, 0.1);
`;
