// src/packages/vega-ui/src/Modal.tsx
import { useState } from "react";
import { createPortal } from "react-dom";

import { useFocusTrap } from "./hooks/useFocusTrap";

export const Modal: React.FC<{
  isOpen: boolean;
  onClose: () => void;
  children?: React.ReactNode;
  canEscapeKeyClose?: boolean;
}> = ({ isOpen, onClose, children }) => {
  const [element, setElement] = useState<HTMLElement | null>(null);
  useFocusTrap({ el: element, isOpen, onClose });

  if (!isOpen) {
    return null;
  }

  return createPortal(
    <div
      ref={setElement}
      style={{
        backgroundColor: "rgba(0, 0, 0, 0.5)",
        position: "absolute",
        top: 0,
        left: 0,
        width: "100vw",
        height: "100vh",
        zIndex: 100,
      }}
    >
      <div
        style={{
          display: "flex",
          width: "100%",
          height: "100%",
          zIndex: 101,
        }}
      >
        {children}
      </div>
    </div>,
    document.body
  );
};

// components/vega/Modal.vue
<template>
  <div v-show="isOpen" ref="modal" class="modal">
    <slot />
  </div>
</template>

<style scoped>
.modal {
  position: fixed;
  top: 0;
  width: 100vw;
  height: 100vh;
  background-color: rgba(0 0 0 / 0.5);
  display: flex;
  z-index: 10;
}
</style>
<script lang="ts">
import Vue from "vue";
import { Component, Ref } from "vue-property-decorator";

@Component({})
export default class Modal extends Vue {
  @Ref() modal?: HTMLElement;

  isOpen: boolean = false;

  mounted() {
    if (this.modal) document.body.append(this.modal);
  }

  open() {
    this.isOpen = true;
  }

  close() {
    this.isOpen = false;
  }
}
</script>
