// src/components/panels/StripUI.vue
<script setup lang="ts">
import { CSSProperties } from "vue";
import { Strip } from "~~/src/core/Strip";
import undo from "~~/src/core/Undo";
import { onDragStart } from "~~/src/utils/onDragStart";
const props = defineProps<{ strip: Strip }>();

const { timeline, moveStrip, selectStrip } = useTimeline();

const layerHeight = 50;
const el = ref<HTMLElement | null>(null);

const pixScale = computed(() => {
  const width = el.value?.parentElement?.getBoundingClientRect().width || 1;
  const viewScale =
    (timeline.value.end - timeline.value.start) / timeline.value.length;
  return width / timeline.value.scale / viewScale;
});

const CUT_LEFT_PX = 50;
const MIN_VISIBLE_WIDTH = 28; // border 4 * 2 + handle 8 * 2 + middle space 4

const hiddenWidth = ref(0);
const style = computed<CSSProperties>(() => {
  let left = (props.strip.start - timeline.value.start) * pixScale.value;
  let width = props.strip.length * pixScale.value;
  // console.log(left);
  if (left < -CUT_LEFT_PX) {
    width += left + CUT_LEFT_PX;
    left = -CUT_LEFT_PX;
  }

  if (width <= MIN_VISIBLE_WIDTH) {
    hiddenWidth.value = MIN_VISIBLE_WIDTH - width;
    width = MIN_VISIBLE_WIDTH;
  } else {
    hiddenWidth.value = 0;
  }

  return {
    width: width + "px",
    position: "absolute",
    top: props.strip.layer * layerHeight + 1 + "px",
    left: left + "px",
  };
});

function drag(e: MouseEvent) {
  e.preventDefault();

  const parent = el.value?.parentElement;
  const parentRect = parent?.getBoundingClientRect();
  if (!parentRect) return;

  const startProps = {
    start: props.strip.start,
    length: props.strip.length,
    id: props.strip.id,
    layer: props.strip.layer,
  };
  let startStart = startProps.start;
  let finalProps = { ...startProps };
  onDragStart(
    e,
    (d, e) => {
      const layerIndex = Math.floor((e.clientY - parentRect.top) / layerHeight);
      if (layerIndex < 0) return;
      startStart += d.x / pixScale.value;
      finalProps = {
        id: startProps.id,
        layer: layerIndex,
        start: startStart,
        length: startProps.length + d.x / pixScale.value,
      };
      moveStrip(
        finalProps.id,
        finalProps.start,
        finalProps.length,
        finalProps.layer
      );
    },
    (e) => {
      undo.push(
        () => {
          moveStrip(
            startProps.id,
            startProps.start,
            startProps.length,
            startProps.layer
          );
        },
        () => {
          moveStrip(
            finalProps.id,
            finalProps.start,
            finalProps.length,
            finalProps.layer
          );
        }
      );
    }
  );
}

function moveStart(e: MouseEvent) {
  e.stopPropagation();
  const firstEnd = props.strip.start + props.strip.length;
  onDragStart(e, (d) => {
    const start = props.strip.start + d.x / pixScale.value;
    if (start > firstEnd) return;
    moveStrip(
      props.strip.id,
      start,
      props.strip.length - d.x / pixScale.value,
      props.strip.layer
    );
  });
}

function moveEnd(e: MouseEvent) {
  e.stopPropagation();
  onDragStart(e, (d) => {
    const length = props.strip.length + d.x / pixScale.value;
    if (length < 0) return;
    moveStrip(props.strip.id, props.strip.start, length);
  });
}

function getComponentNameFromStrip(strip: Strip) {
  for (let i = 0; i < strip.effects.length; i++) {
    const effect = strip.effects[i];
    if (effect.type == "Text") {
      return "PanelsTextStripUI";
    } else if (effect.type == "Video") {
      return "PanelsVideoStripUI";
    }
  }
}
</script>

<template>
  <div
    ref="el"
    :style="style"
    class="strip"
    :class="
      timeline.selectedStrips.find((x) => x.id == props.strip.id)
        ? 'strip-selected'
        : ''
    "
    @mousedown="drag"
    @click.stop="() => selectStrip([props.strip.id])"
  >
    <div class="handle" @mousedown="moveStart"></div>
    <component
      :is="getComponentNameFromStrip(props.strip)"
      :strip="props.strip"
    />
    <div class="handle" style="right: 0" @mousedown="moveEnd"></div>
    <div
      class="absolute -right-[4px] -top-[4px] h-[49px]"
      style="background-color: rgba(0, 0, 0, 0.5)"
      :style="{
        width: hiddenWidth + 'px',
      }"
    ></div>
  </div>
</template>

<style scoped>
.strip {
  background-color: var(--teal-200);
  border: 4px solid var(--teal-200);
  box-sizing: border-box;
  cursor: pointer;
  height: 48px;
}

.strip-selected {
  /* background-color: var(--teal-500); */
  border: 4px solid var(--teal-50);
  box-sizing: border-box;
}

.handle {
  position: absolute;
  top: 0;
  width: 8px;
  background-color: var(--teal-300);
  height: 100%;
  cursor: ew-resize;
  z-index: 1;
  user-select: none;
}
</style>

// src/components/timeline_panel/StripUI.tsx
import { FC, useEffect, useRef } from "react";
import styled from "styled-components";

import { Strip } from "@/core/types";

import { AudioEffectStripUI } from "./AudioEffectStripUI";
import { ImageEffectStripUI } from "./ImageEffectStripUI";
import { TextEffectStripUI } from "./TextEffectStripUI";
import { VideoEffectStripUI } from "./VideoEffectStripUI";

export const STRIP_HEIGHT = 20;
export const STRIP_GAP = 1;

export const StripUI: FC<
  Strip & {
    pxPerSec: number;
    offset: number;
    fps: number;
    selected: boolean;
    invalid: boolean;
    onStripChange: (strip: Strip) => void;
    onClick: () => void;
    onMouseDown: (e: React.MouseEvent) => void;
    onMouseDownLeftHandle: (e: React.MouseEvent) => void;
    onMouseDownRightHandle: (e: React.MouseEvent) => void;
  }
> = (props) => {
  const left = (props.start - props.offset) * props.pxPerSec;
  const width = props.length * props.pxPerSec;

  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {});

  const firstEffect = props.effects[0];
  if (firstEffect === undefined) return null;

  if (left + width < 0) return null;

  return (
    <StripUIRoot
      ref={ref}
      style={{
        left: `${left}px`,
        width: `${props.length * props.pxPerSec}px`,
        height: `${STRIP_HEIGHT}px`,
        top: `${props.layer * STRIP_HEIGHT + STRIP_GAP * props.layer}px`,
        zIndex: props.invalid ? 100 : 0,
      }}
      selected={props.selected}
      onMouseDown={props.onMouseDown}
    >
      {firstEffect.type === "text" && <TextEffectStripUI strip={props} />}
      {firstEffect.type === "image" && <ImageEffectStripUI strip={props} />}
      {firstEffect.type === "video" && <VideoEffectStripUI strip={props} />}
      {firstEffect.type === "audio" && <AudioEffectStripUI strip={props} />}
      <StripHandle
        onMouseDown={props.onMouseDownLeftHandle}
        style={{ left: "1px" }}
      />
      <StripHandle
        onMouseDown={props.onMouseDownRightHandle}
        style={{ right: "1px" }}
      />
      {props.invalid && <InvalidDiv />}
    </StripUIRoot>
  );
};

const InvalidDiv = styled.div`
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  background-color: rgba(255, 0, 0, 0.64);
  border-radius: 4px;
`;

const StripUIRoot = styled.div<{ selected: boolean }>`
  position: absolute;
  background-color: var(--color-text-strip);
  user-select: none;
  box-sizing: border-box;
  overflow: hidden;
  display: flex;
  border: 1px solid
    ${(props) =>
      props.selected
        ? "var(--color-strip-selected)"
        : "var(--color-text-strip-border)"};
`;

const StripHandle = styled.div`
  position: absolute;
  top: 0;
  bottom: 0;
  width: 4px;
  top: 0px;
  background-color: var(--color-strip-handle);
  cursor: ew-resize;
`;
