// src/components/panels/AssetPanel.vue
<script setup lang="ts">
import { uuid } from 'short-uuid'
import { IAsset } from '~~/src/core/IAsset'

const { assets, addAsset, removeAsset } = useAssets()
const { startDad } = useDragAndDrop()

function drop (e: DragEvent) {
  e.preventDefault()
  const file = e.dataTransfer?.files[0]
  if (!file) {
    return
  }

  addAsset({
    id: uuid(),
    name: file.name,
    path: file.name,
    type: extentionToType(getExt(file.name))
  })
}

function getExt (name: string) {
  return name.split('.').pop() || ''
}

function extentionToType (ext: string) {
  switch (ext) {
    case 'jpg':
    case 'jpeg':
    case 'png':
    case 'gif':
      return 'Image'
    case 'mp4':
    case 'webm':
    case 'ogg':
      return 'Video'
    case 'mp3':
    case 'wav':
      return 'Audio'
    default:
      return 'unknown'
  }
}

function dragover (e: DragEvent) {
  e.preventDefault()
}

function dragstart (e: MouseEvent, id: string) {
  startDad(e, 'assets', id, `asset-list-item-${id}`)
}

function selectAsset (asset: IAsset) {
  assets.value.selectedAssets = [asset]
}

function isSelectedAsset (asset: IAsset) {
  return assets.value.selectedAssets.includes(asset)
}

const el = ref<HTMLElement | null>(null)
const focus = () => {
  el.value?.focus()
}
onMounted(() => {
  el.value?.addEventListener('keydown', (e) => {
    if (e.key === 'x') {
      if (assets.value.selectedAssets.length > 0) {
        removeAsset(assets.value.selectedAssets[0])
      }
    }
  })
})
</script>

<template>
  <div
    ref="el"
    style="height: 100%"
    tabindex="0"
    @click="focus"
    @drop="drop"
    @dragover="dragover"
  >
    <div
      v-for="(asset, i) in assets.assets"
      :id="`asset-list-item-${asset.id}`"
      :key="i"
      class="asset-list-item"
      :style="{
        backgroundColor: isSelectedAsset(asset) ? 'darkgray' : 'transparent'
      }"
      @click="() => selectAsset(asset)"
      @mousedown="e => dragstart(e, asset.id)"
    >
      <component
        :is="asset.type.toLowerCase() + '-asset-list-item'"
        :asset="asset"
      />
    </div>
  </div>
</template>

<style scoped>
.asset-list-item {
  white-space: nowrap;
  user-select: none;
  display: flex;
  cursor: pointer;
  height: 32px;
  overflow: hidden;
  border-bottom: 1px solid var(--border-grey);
  background-color: #111;
  color: #fff;
}

.asset-list-item:hover {
  background-color: rgba(0, 0, 0, 0.1);
}
</style>

// src/components/assets_panel/AssetPanel.tsx
import { FC } from "react";
import { useDispatch } from "react-redux";
import { uuid } from "short-uuid";
import styled from "styled-components";
import {
  FilePlus,
  Music,
  Phone,
  Photo,
  PlayerPause,
  Tex,
  Trash,
  Video,
} from "tabler-icons-react";
import { Asset } from "../../interfaces/asset/Asset";
import { ImageAsset } from "../../interfaces/asset/ImageAsset";
import { VideoAsset } from "../../interfaces/asset/VideoAsset";
import { FontAsset } from "../../interfaces/asset/FontAsset";
import { filePick } from "../../utils/filePick";
import { isAudioAsset, isImageAsset } from "../../rendering/updateTextEffect";
import { actions } from "../../store/scene";
import { useSelector } from "../../store/useSelector";
import { Panel } from "../core/Panel";
import { IconButton } from "../core/styled/IconButton";
import { iconProps } from "../core/iconProps";
import { ToolTip } from "../core/styled/ToolTip";
import { AudioAsset } from "@/interfaces/asset/AudioAsset";

const supportedVideoExtensions = ["mp4", "webm"];
const supportedFontExtensions = ["ttf"];
const supportedAudioExtensions = ["mp3", "wav"];
const supportedImageExtensions = ["png", "jpg", "jpeg", "svg"];

function isImage(path: string) {
  return supportedImageExtensions.some((ext) => path.endsWith(ext));
}

function isVideo(path: string) {
  return supportedVideoExtensions.some((ext) => path.endsWith(ext));
}

function isFont(path: string) {
  return supportedFontExtensions.some((ext) => path.endsWith(ext));
}
function isAudio(path: string) {
  return supportedAudioExtensions.some((ext) => path.endsWith(ext));
}

export const AssetPanel: FC = () => {
  const assets = useSelector((state) => state.scene.assets);
  const selectedAssetIds = useSelector((state) => state.scene.selectedAssetIds);
  const dispatch = useDispatch();
  const handleSelectAsset = (asset: Asset) => {
    dispatch(actions.setSelectedAssetIds([asset.id]));
  };

  const handleAddAsset = () => {
    const accept = [
      ...supportedVideoExtensions,
      ...supportedFontExtensions,
      ...supportedImageExtensions,
    ].join(", ");
    filePick((_, path) => {
      if (isFont(path)) {
        const asset: FontAsset = {
          id: uuid(),
          path: `file://${path}`,
          type: "font",
          name: path.split("/").join("_"),
        };
        dispatch(actions.updateAssets(asset));
      } else if (isVideo(path)) {
        const asset: VideoAsset = {
          id: uuid(),
          path: `file://${path}`,
          type: "video",
          name: path.split("/").join("_"),
        };
        dispatch(actions.updateAssets(asset));
      } else if (isImage(path)) {
        const asset: ImageAsset = {
          id: uuid(),
          path: `file://${path}`,
          type: "image",
          name: path.split("/").join("_"),
        };
        dispatch(actions.updateAssets(asset));
      } else if (isAudio(path)) {
        const asset: AudioAsset = {
          id: uuid(),
          path: `file://${path}`,
          type: "audio",
          name: path.split("/").join("_"),
        };
        dispatch(actions.updateAssets(asset));
      } else {
        alert("Unsupported file type");
      }
    }, accept);
  };

  const handleDeleteAsset = () => {
    dispatch(actions.removeAsset(selectedAssetIds));
  };

  return (
    <Panel height={100} width={100}>
      <div
        style={{
          marginBottom: "8px",
          display: "flex",
          gap: "2px",
        }}
      >
        <IconButton onClick={handleAddAsset}>
          <FilePlus {...iconProps} />
          <ToolTip>Add new asset</ToolTip>
        </IconButton>
        <IconButton onClick={handleDeleteAsset}>
          <Trash {...iconProps} />
          <ToolTip>Delete selected asset</ToolTip>
        </IconButton>
      </div>
      {assets.map((asset) => {
        return (
          <AssetListItem
            key={asset.id}
            asset={asset}
            selected={selectedAssetIds.includes(asset.id)}
            onClick={() => handleSelectAsset(asset)}
          />
        );
      })}
    </Panel>
  );
};

const AssetListItem: FC<{
  asset: Asset;
  selected: boolean;
  onClick: () => void;
}> = (props) => {
  return (
    <Div
      tabIndex={0}
      onClick={props.onClick}
      style={{
        backgroundColor: props.selected ? "#444" : "transparent",
      }}
    >
      {props.asset.type === "video" ? (
        <Video style={{ margin: "auto 2px", minWidth: "16px" }} size={16} />
      ) : props.asset.type === "font" ? (
        <Tex style={{ margin: "auto 2px", minWidth: "16px" }} size={16} />
      ) : isImageAsset(props.asset) ? (
        <Photo style={{ margin: "auto 2px", minWidth: "16px" }} size={16} />
      ) : isAudioAsset(props.asset) ? (
        <Music style={{ margin: "auto 2px", minWidth: "16px" }} size={16} />
      ) : null}
      <div>{props.asset.name}</div>
    </Div>
  );
};

const Div = styled.div`
  display: flex;
  color: white;
  white-space: nowrap;
  overflow: hidden;
  font-family: "Ricty Diminished";
  line-height: 16px;
  font-size: 12px;
  height: 16px;
  cursor: default;
  user-select: none;
  box-sizing: border-box;

  :hover {
    background-color: #333;
  }

  :focus {
    background-color: #444;
    border-bottom: 1px solid #fff;
  }
`;
